import Link from 'next/link'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { sql } from '@/lib/db'
import { baseUrl, qrSvg, roomUrl } from '@/lib/qr'
import { readCardLink } from '@/lib/staff-link'

export const dynamic = 'force-dynamic'

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Your room · HConcierge',
    // Carries a room's access code. Same treatment as a guest room link.
    robots: { index: false, follow: false },
  }
}

/**
 * The welcome card, on the guest's own phone.
 *
 * This is what the front desk sends by WhatsApp at check-in. It shows the same
 * two things the printed card does — the QR and the four digits — so a guest who
 * has lost the paper, or never took it, still has them.
 *
 * Three things keep it safe enough to be a link somebody can forward:
 *
 *   - The token is signed and names a room, not a stay, so it cannot be edited
 *     into another room's card.
 *   - The room is re-read here on every open, and an unoccupied room refuses.
 *     Checking out therefore kills every copy of this link immediately, which
 *     matters far more than the token's own three-day expiry.
 *   - It never renders anything about the stay beyond the guest's own name.
 *     No folio, no request history, no messages.
 *
 * Deliberately a server component with no client JavaScript: it is opened once,
 * on hotel wifi, from a chat app's in-app browser.
 */
export default async function CardPage({ params }: PageProps<'/c/[token]'>) {
  const { token } = await params

  const link = readCardLink(token)
  if (!link) notFound()

  const [room] = await sql<
    {
      number: string
      token: string
      guest_name: string | null
      access_code: string | null
      occupied: boolean
      property_name: string
      property_phone: string | null
      brand_color: string
    }[]
  >`select r.number, r.token, r.guest_name, r.access_code, r.occupied,
           p.name as property_name, p.phone as property_phone, p.brand_color
      from rooms r join properties p on p.id = r.property_id
     where r.id = ${link.roomId} limit 1`

  // An empty room's card is nobody's business, and this is the check that makes
  // checking out revoke the link rather than waiting for the expiry.
  if (!room || !room.occupied || !room.access_code) notFound()

  const base = await baseUrl()
  const svg = await qrSvg(roomUrl(base, room.token), 260)

  return (
    <main
      className="mx-auto flex min-h-dvh max-w-md flex-col items-center justify-center px-6 py-12 text-center"
      style={{ ['--brand' as string]: room.brand_color }}
    >
      <p className="text-[12px] font-semibold tracking-[0.18em] text-[var(--brand)] uppercase">
        {room.property_name}
      </p>
      <h1 className="mt-3 text-[40px] leading-none font-semibold tracking-tight">Room {room.number}</h1>
      {room.guest_name && <p className="text-muted mt-2 text-[15px]">{room.guest_name}</p>}

      <div className="border-line bg-surface mt-8 w-full rounded-2xl border p-6">
        <p className="text-muted text-[11px] font-semibold tracking-[0.16em] uppercase">Your code</p>
        <p className="mt-2 text-[52px] leading-none font-semibold tracking-[0.2em] indent-[0.2em] tabular-nums">
          {room.access_code}
        </p>

        <div
          className="mt-7 flex justify-center [&>svg]:h-[220px] [&>svg]:w-[220px]"
          // Generated by the qrcode package from a URL we built ourselves.
          dangerouslySetInnerHTML={{ __html: svg }}
        />

        {/* On the phone that received this, tapping is the whole point — the QR
            is for the other devices in the room. */}
        <Link
          href={`/r/${room.token}`}
          className="bg-ink mt-7 block w-full rounded-xl px-4 py-3.5 text-[15px] font-semibold text-white"
        >
          Open it on this phone
        </Link>
      </div>

      <p className="text-muted mt-7 text-[14px] leading-relaxed">
        Room service, housekeeping, laundry, the front desk — anything at all, without calling down.
      </p>
      <p className="text-faint mt-4 text-[12px]">
        No app to install.{room.property_phone ? ` Prefer to call? ${room.property_phone}` : ''}
      </p>
    </main>
  )
}
