import Link from 'next/link'
import { requireOperational, requireManager } from '@/lib/auth'
import { sql } from '@/lib/db'
import { scopeTo } from '@/lib/scope'
import { baseUrl, qrSvg, roomUrl } from '@/lib/qr'
import PrintButton from './PrintButton'

export const dynamic = 'force-dynamic'

type Row = {
  id: string
  number: string
  token: string
  guest_name: string | null
  access_code: string | null
  property_name: string
  property_phone: string | null
  brand_color: string
}

export default async function PrintPage({ searchParams }: PageProps<'/staff/rooms/print'>) {
  const { property, room, slip } = await searchParams
  const propertyId = typeof property === 'string' ? property : null
  const roomId = typeof room === 'string' ? room : null
  // A welcome card carries the stay's code; a desk card is permanent and does not.
  const isSlip = slip === '1' && Boolean(roomId)
  // Anyone may print the permanent desk card. The welcome card is the guest's
  // credential, so printing one is a front-desk job.
  const staff = isSlip ? await requireManager() : await requireOperational()

  const rooms = await sql<Row[]>`
    select r.id, r.number, r.token, r.guest_name, r.access_code,
           p.name as property_name, p.phone as property_phone, p.brand_color
      from rooms r join properties p on p.id = r.property_id
     where ${scopeTo(staff, sql`r.property_id`, propertyId)}
       and ${roomId ? sql`r.id = ${roomId}` : sql`true`}
     order by p.name, r.number`

  const base = await baseUrl()
  const cards = await Promise.all(
    rooms.map(async (r) => ({ ...r, svg: await qrSvg(roomUrl(base, r.token)) })),
  )

  return (
    <div className="mx-auto max-w-[1100px] px-4 py-6">
      <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-[22px] font-semibold tracking-tight">
            {isSlip ? 'Welcome card' : `${cards.length} desk card${cards.length === 1 ? '' : 's'}`}
          </h1>
          <p className="text-muted mt-1 max-w-[65ch] text-sm">
            {isSlip
              ? 'Hand this to the guest at check-in. It carries their code, so it should not be left in the room.'
              : 'Print, cut along the borders and stand one on each desk. These are permanent — the code on the guest’s welcome card is what changes between stays.'}
          </p>
        </div>
        <div className="flex gap-2">
          <Link href="/staff/rooms" className="border-line rounded-xl border px-4 py-2.5 text-[13px] font-semibold">
            Back to rooms
          </Link>
          <PrintButton />
        </div>
      </div>

      {/* A welcome card is one sheet handed to one person, so it gets the whole
          sheet: A4 at full height, type sized for the page rather than for a
          420px column floating in the top third of it. The desk cards stay
          two-up and small, because they are cut apart and stood on furniture. */}
      {isSlip ? (
        cards.map((c) => (
          <article
            key={c.id}
            className="mx-auto flex h-[297mm] w-full max-w-[210mm] flex-col items-center justify-between px-[20mm] py-[22mm] text-center print:h-screen print:max-w-none"
            style={{ ['--brand' as string]: c.brand_color }}
          >
            <div className="w-full">
              <p className="text-[15px] font-semibold tracking-[0.2em] text-[var(--brand)] uppercase">
                {c.property_name}
              </p>
              <p className="mt-4 text-[74px] leading-[0.95] font-semibold tracking-tight">Room {c.number}</p>
              {c.guest_name && <p className="text-muted mt-3 text-[26px]">{c.guest_name}</p>}
            </div>

            <div className="w-full">
              <p className="text-[25px] leading-snug font-medium">
                Scan for room service, housekeeping,
                <br />
                laundry, the front desk — anything at all.
              </p>
              <div
                className="mt-[8mm] flex justify-center [&>svg]:h-[300px] [&>svg]:w-[300px]"
                // Generated by the qrcode package from a URL we built ourselves.
                dangerouslySetInnerHTML={{ __html: c.svg }}
              />
            </div>

            {c.access_code ? (
              <div className="w-full">
                <p className="text-muted text-[15px] font-semibold tracking-[0.2em] uppercase">Your code</p>
                <p className="mt-3 text-[96px] leading-none font-semibold tracking-[0.22em] indent-[0.22em] tabular-nums">
                  {c.access_code}
                </p>
                <p className="text-muted mt-5 text-[21px] leading-relaxed">
                  Enter it once after scanning. This phone then stays
                  <br />
                  signed in until you check out.
                </p>
              </div>
            ) : (
              <p className="text-muted text-[22px]">No code issued — check the guest in first.</p>
            )}

            <p className="text-faint text-[17px]">
              No app to install.{c.property_phone ? ` Prefer to call? ${c.property_phone}` : ''}
            </p>
          </article>
        ))
      ) : (
        // `@page { margin: 0 }` in globals.css is what removes the browser's
        // printed URL from the welcome card, but it applies to every printed
        // page — so the desk cards have to supply their own margin or they land
        // flush against a paper edge no consumer printer can reach, and the
        // dashed cut lines get clipped. 10mm clears every printer.
        //
        // A line comment, not `{/* */}`: this branch of the ternary may hold
        // exactly one expression, and a JSX comment beside the div is a second.
        <div className="grid grid-cols-2 gap-4 print:gap-0 print:p-[10mm]">
          {cards.map((c) => (
            <article
              key={c.id}
              className="border-line flex break-inside-avoid flex-col items-center rounded-2xl border p-6 text-center print:rounded-none print:border-dashed"
              style={{ ['--brand' as string]: c.brand_color }}
            >
              <p className="text-[11px] font-semibold tracking-[0.16em] text-[var(--brand)] uppercase">
                {c.property_name}
              </p>
              <p className="mt-2 text-[34px] leading-none font-semibold tracking-tight">Room {c.number}</p>

              <p className="text-muted mt-3 text-[13px] leading-snug">
                Scan for room service, housekeeping,
                <br />
                laundry, the front desk — anything at all.
              </p>

              <div
                className="mt-4 [&>svg]:h-[190px] [&>svg]:w-[190px]"
                dangerouslySetInnerHTML={{ __html: c.svg }}
              />

              <p className="text-faint mt-4 text-[11px]">
                No app to install. {c.property_phone ? `Prefer to call? ${c.property_phone}` : ''}
              </p>
            </article>
          ))}
        </div>
      )}

      {cards.length === 0 && <p className="text-faint py-16 text-center text-sm">No rooms to print.</p>}
    </div>
  )
}
